export const lightTheme = {
  background: "#f3f4f6",
  surface: "#ffffff",
  primary: "#e94560",
  secondary: "#e5e7eb",
  text: "#111827",
  textSecondary: "#6b7280",
  border: "#d1d5db",
  input: "#ffffff",
  error: "#ef4444",
  success: "#10b981",
  navigationBar: "#ffffff",
  navigationButtons: "dark",
  card: "#ffffff",
  status: {
    accepted: { background: "#d1fae5", text: "#065f46", label: "Aceito" },
    waiting: { background: "#f3f4f6", text: "#374151", label: "Aguardando" },
    rejected: { background: "#fee2e2", text: "#991b1b", label: "Recusado" },
    pending: { background: "#fef3c7", text: "#92400e", label: "Pendente" },
  },
  chat: {
    bubbleSent: "#1d8cf8", // Azul vibrante para mensagens enviadas
    textSent: "#ffffff",
    bubbleReceived: "#ffffff",
    textReceived: "#111827",
    proposalCard: "#ffffff",
    actionButton: {
      accept: "#10b981",
      reject: "#f87171",
      suggest: "#e5e7eb",
      textSuggest: "#374151",
    },
  },
  profile: {
    avatarEdit: "#3b82f6",
    sectionTitle: "#6b7280",
    iconBackground: "#f3f4f6",
    logout: "#ef4444",
    logouText: "#ffffff",
    contaners: "#ffffff",
    avatarBorder: "#d1d5db",
    btnAvatarBorder: "#ffffff",
  },
  calendar: {
    backgroundColor: "#f3f4f6",
    calendarBackground: "#f3f4f6",
    textSectionTitleColor: "#b6c1cd",
    selectedDayBackgroundColor: "#e94560",
    selectedDayTextColor: "#ffffff",
    todayTextColor: "#3b82f6",
    dayTextColor: "#2d4150",
    textDisabledColor: "#d9e1e8",
    dotColor: "#00adf5",
    selectedDotColor: "#ffffff",
    arrowColor: "#3b82f6",
    disabledArrowColor: "#d9e1e8",
    monthTextColor: "#3b82f6",
    indicatorColor: "#3b82f6",
    textDayFontWeight: "300",
    textMonthFontWeight: "bold",
    textDayHeaderFontWeight: "300",
    textDayFontSize: 16,
    textMonthFontSize: 16,
    textDayHeaderFontSize: 16,
    types: {
      workDay: "#fbbf24",
      noturnoDay: "#003680",
      extraDay: "#FA8805",
      extraNoturnoDay: "#2F0080",
      exchangeDay: "#C9FB13",
      exchangeNoturnoDay: "#005F66",
    },
  },

  // Estilos de Componentes Específicos
  components: {
    icons: {
      color: "#3b82f6",
      backgroundColor: "#e5e7eb",
    },
    typeSelector: {
      backgroundColor: "#e5e7eb",
    },
    typeButton: {
      activeBackgroundColor: "#e94560",
      inactiveBackgroundColor: "transparent",
    },
    typeButtonActive: {
      backgroundColor: "#3b82f6",
    },
    typeText: {
      activeColor: "#ffffff",
      inactiveColor: "#6b7280",
    },
    loginButton: {
      backgroundColor: "#3b82f6",
      text: "#ffffff",
    },
    forgotButton: {
      text: "#6b7280",
    },
  },
};
